version: '3.3'

services:
  db:
    image: mysql:5.7

    volumes:
      - db_data:/var/lib/mysql
      - './data:/docker-entrypoint-initdb.d'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - mongonet

# Workflow: when making changes to the website via the gui, remember to exec
# into the container and commit.  then exit the container and pull from the
# host.  the code will go into the upcgold_code directory, and then mount it
# below
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - './Divi:/var/www/html/wp-content/themes/Divi'
      - './Extra:/var/www/html/wp-content/themes/Extra'
      - './bloom:/var/www/html/wp-content/plugins/bloom'
      - './monarch:/var/www/html/wp-content/plugins/monarch'
      - './php.ini:/usr/local/etc/php/conf.d/php.ini'

    ports:
      - "4447:4447"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      VIRTUAL_HOST: appfront.upcgold.io
      LETSENCRYPT_HOST: appfront.upcgold.io
    networks:
      - mongonet

volumes:
    db_data: {}

networks:
  mongonet:
    external: true
